---
title: "Quality check 03, List blocks in block groups split by community districts"
author: "Satya Golla and Steve Simon"
date: "Created 2023-03-30"
output: html_document
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding,
  output_dir = "../results", output_format = "all") })  
---

This program lists blocks within block groups that only partially intersect with community districts.

### Load relevant files

```{r setup}
# Important abbreviations:
#    bg = block group
#    bl = block
#    cd = community district
#    co = county
#    nbd=neighborhood
#    tr = tract

library(glue)
library(magrittr)
library(sf)
library(tidyverse)
library(dplyr)
path_name <- "../data/"
```

### Contents of bg

```{r}
load(glue("{path_name}bg.RData"))
glimpse(bg)
```

### Contents of bl

```{r}
load(glue("{path_name}bl.RData"))
glimpse(bl)
```

### Contents of cd

```{r}
load(glue("{path_name}cd.RData"))
glimpse(cd)
```

### Contents of co

```{r}
load(glue("{path_name}co.RData"))
glimpse(co)
```

### Contents of cd-intersections

```{r}
load(glue("{path_name}cd-intersections.RData"))
glimpse(bg_cd_intersection)
glimpse(bl_cd_intersection)
```

### Contents of cd-weights

```{r}
load(glue("{path_name}cd-weights.RData"))
glimpse(bg_counts)
glimpse(bg_list)
glimpse(bl_counts)
glimpse(bl_list)
```

### Contents of red

```{r}
load(glue("{path_name}red.RData"))
glimpse(red)
```

### Subset co to seven counties

```{r}
clist <- c(
  "20091",
  "20103",
  "20209",
  "29037",
  "29047",
  "29095",
  "29165")
co                                     %>%
  filter(GEOID %in% clist)             -> co
glimpse(co)
```

### Get id values for all community districts

```{r}
cd                                     %>%
  tibble                               %>%
  distinct(cd_id)                      %>%
  arrange(cd_id)                       %>%
  pull(cd_id)                           -> cd_list
```

### Draw an overview map

```{r}
co_points <- st_point_on_surface(co)
co_coords <- as.data.frame(st_coordinates(co_points))
co_coords$NAME <- co$NAME

ggplot()+
  geom_sf(
    data=co, 
    color="darkred", 
    fill=NA)                            +
  geom_text(
    data=co_coords, 
    aes(X, Y, label=NAME))              +
  xlab("Longitude")                     +
  ylab("Latitude")                      -> overview_map
plot(overview_map)
```

### High level view

```{r pull-interesting-cd-ids}
name_list <- c(
  "Brookside",
  "Midtown",
  "Swope Park",
  "Waldo",
  "Ward Parkway",
  "Greater Downtown",
  "Antioch",
  "Little Blue Valley",
  "Rosedale",
  "Argentine")

cd                                     %>%
  filter(cd_name %in% name_list)       %>%
  pull(cd_id)                           -> interesting_cd
```

```{r pull-information}
pick_bg <- function(da, i_bg) {
  # Use this with
  #    bg
  #    bl
  da                                  %>%
    filter(bg_id %in% i_bg)           %>%
    return
}

pick_bg_cd <- function(da, i_bg, i_cd) {
  # Use this with
  #   bg_cd_intersection
  #   bg_counts
  #   bl_counts
  #   red
  da                                  %>%
    filter(bg_id %in% i_bg)           %>%
    filter(cd_id %in% i_cd)           %>%
    return
}

pick_bl <- function(da, i_bg) {
  # Use this with
  #    bl
  da                                  %>%
    filter(bg_id %in% i_bg)           %>%
    return
}

pick_bl_cd <- function(da, i_bl, i_cd) {
  # Use this with
  #   bl_cd_intersection
  #   bl_counts
  #   red
  da                                  %>%
    filter(bl_id %in% i_bl)           %>%
    filter(cd_id %in% i_cd)           %>%
    return
}

pick_cd <- function(da, i_cd) {
  # Use this with
  #    cd
  da                                  %>%
    filter(cd_id %in% i_cd)           %>%
    return
}

```

```{r plot-pieces}
terse <- TRUE
calc_cd_subset <- function(cd, i_cd) {
  cd_subset <- cd[cd$cd_id==i_cd, ]
  if (terse) return(cd_subset)
  cat(glue("i_cd = {i_cd}"))
  cat("cd_subset")
  glimpse(cd_subset)
  return(cd_subset)  
}

plot_co_cd <- function(overview_map, cd_subset) {
  # Draw community district in green atop
  # counties outlined in red
  ti <- cd_subset$cd_name
  overview_map                          +
    ggtitle(ti)                         +
    geom_sf(
      data=cd_subset,
      aes(),
      fill="lightgreen",
      color=NA)
}

calc_bg_subset <- function(bg_cd_interestion, i_cd) {
  bg_cd_intersection                   %>%
    filter(cd_id==i_cd)                %>%
    filter(bg_prop_in > 0.10)          %>%
    pull(bg_id)                         -> bg_list
  bg                                   %>%
    filter(bg_id %in% bg_list)          -> bg_subset
  if (terse) return(bg_subset)
  cat("bg_subset")
  glimpse(bg_subset)
  return(bg_subset)
}

calc_bg_text <- function(bg_subset) {
  bg_points <- st_point_on_surface(bg_subset)
  bg_coords <- as.data.frame(st_coordinates(bg_points))
  bg_coords$NAME <- str_sub(bg_subset$bg_id, 6, 12)
  bg_coords
  if (terse) return(bg_coords)
  cat("bg_coords")
  glimpse(bg_coords)
  return(bg_coords)
}

plot_cd <- function(cd_subset) {
  # draw community districts in green
  ti <- cd_subset$cd_name
  ggplot(cd_subset)                     +
    ggtitle(ti)                         +
    xlab("Longitude")                   +
    ylab("Latitude")                    +
      geom_sf(
        data=cd_subset,
        aes(),
        fill="lightgreen",
        color=NA)
}

overlay_bg_borders <- function(cd_map, bg_subset) {
  cd_map                               +
    geom_sf(
      data=bg_subset,
      aes(),
      fill=NA,
      color="darkred")    
}

overlay_bg_text <- function(cd_map, bg_coords) {
  cd_map                                +
    geom_text(
      data=bg_coords, 
      aes(X, Y, label=NAME))
}
```

```{r loop, warnings=FALSE, message=FALSE}
for (i_cd in interesting_cd[1:3]) {
  # Pick subsets
  cd %>% pick_cd(i_cd) -> cd_subset
  bg_cd_intersection                  %>%
    pick_cd(i_cd)                     %>%
    select(bg_id, bg_prop_in)         %>%
    filter(bg_prop_in > 0.1)           -> bg_list
  bg                                  %>%
    filter(bg_id %in% bg_list$bg_id)   -> bg_subset
  bg_coords <- calc_bg_text(bg_subset)

  print(glue("Start processing for {cd_subset$cd_name}"))
  print("bg_list"); glimpse(bg_list)
  print("bg_subset"); glimpse(bg_subset)
  print("bg_coords"); glimpse(bg_coords)

  # plot overview
  plot_co_cd(overview_map, cd_subset)  -> o_map
  # plot(o_map)
  
  # plot intersecting block groups
  plot_cd(cd_subset)                  %>%
    overlay_bg_borders(bg_subset)     %>%
    overlay_bg_text(bg_coords)         -> i_map
  # plot(i_map)
  
  # remove interior block groups
  bg_list %<>% filter(bg_prop_in <= 0.9)
  if (nrow(bg_list)==0) next
  print(glue("Entering loop for {cd_subset$cd_name}"))
  for (i_bg in bg_list$bg_id) {
    print(glue("Looping index = {i_bg}"))
    bl$bg_id <- str_sub(bl$bl_id, 1, 12)
    bl %>% pick_bg(i_bg)                -> bl_subset
    print("bg_counts")
    bg_counts                          %>%
      pick_bg_cd(i_bg, i_cd)           %>%
      data.frame                        -> view_bg_counts
    view_bg_counts                     %>%
      print
        print("bl_counts")
    bl_counts                          %>%
      pick_bg_cd(i_bg, i_cd)           %>%
      mutate(
        prop_in = round(100*prop_in))  %>%
      data.frame                        -> view_bl_counts
    view_bl_counts                     %>%
      print 
    
    print("bg_cd_intersection")
    bg_cd_intersection                 %>%
      pick_bg_cd(i_bg, i_cd)           %>%
      mutate(
        bg_prop_in = 
          round(100*bg_prop_in))       %>%
      data.frame                        -> view_bl_cd
    view_bl_cd                         %>%
      print 
    
    print("red-file")
    red                                %>%
      pick_bg(i_bg)                    %>%
      data.frame                        -> view_red
    view_red                           %>%
      print 
    
    

  }
  print(
    glue(
      "Completed all loops for {cd_subset$cd_name}"))

  # draw community districts in green with
  # block groups outlined in red.

  # draw block groups and blocks outlined
  # in red atop community district in green.
}
```

```{r, eval=FALSE}
  for (i_bg in bg_subset$bg_id) {
    # Plot community district
    ggplot(cd_subset)                   +
      ggtitle(ti)                       +
      xlab("Longitude")                 +
      ylab("Latitude")                  +
      geom_sf(
        data=cd_subset,
        aes(),
        fill="lightgreen",
        color=NA) -> map3
    # Overlay blocks associated with a block group
    map3                                +
      geom_sf(
        data=bl_subset,
        aes(),
        fill=NA,
        color="darkred")                +
      ggtitle(i_bg)                     -> map4
    plot(map4)

    # Recalculate intersections
    cd_subset                         %>%
      st_intersection(bl_subset)       -> intersect_subsets
    print("intersect_subsets")
    glimpse(intersect_subsets)

    # Associate text with interior data points
    bl_subset                          %>%
      inner_join(red, by="bl_id")      %>%
      mutate(
        bl_id=str_sub(bl_id, 13, 15))   -> bl_labels
    bl_labels                          %>%
      st_point_on_surface              %>%
      st_coordinates                   %>%
      data.frame                       %>%
      bind_cols(bl_labels)              -> bl_text
    print("bl_labels")
    glimpse(bl_labels)
    print("bl_text")
    glimpse(bl_text)
    save(bl_text, file=glue("../data/bg_{i_bg}.RData"))

    # Close-up plot of just the blocks
    ggplot(intersect_subsets)           +
      xlab("Longitude")                 +
      ylab("Latitude")                  +
      geom_sf(
        aes(),
        fill="green",
        color="green")                  +
      geom_sf(
        data=bl_subset,
        aes(),
        fill=NA,
        color="darkred")                +
      ggtitle(i_bg)                     -> map5
    plot(map5)
    next
    # Overlay block id
    map5                                +
      geom_text(
        data=bl_text,
        aes(x=X, y=Y, label=bl_id))     +
      ggtitle("Block ids, {i_bg}")     %>%
    plot

    # Overlay people count
    map5                                +
      geom_text(
        data=bl_text,
        aes(x=X, y=Y, label=people))    +
      ggtitle("People, {i_bg}")        %>%
    plot

    # Overlay housing unit count
    map5                                +
      geom_text(
        data=bl_text,
        aes(x=X, y=Y, label=units))     +
      ggtitle("Housing units, {i_bg}") %>%
    plot
  }
}
```
